permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""

title: "Cheenwe"
email: "cxhyun@126.com"
description: "A Ruby Coder"
beian: "豫ICP备16011691号"
github_username:  "cheenwe"
swiftype_searchId: "9TDAXeK2smEEtWndRZJB"
disqus_shortname: "cheenwecn"
duoshuo_shortname: "cheenwe"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js, toc.js]



url: "https://cheenwe.github.io"
imgrepo: "https://cheenwe.github.io/static/img"

# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"

